$FileOwner root
$FileGroup root
$FileCreateMode 0640
$DirCreateMode 0750
$Umask 0027

module(load="imudp")
input(type="imudp" port="514")

template(name="HAProxyLogFormat" type="string" string="%timegenerated% %HOSTNAME% %syslogseverity-text% %programname%:%msg%\n")

if ($syslogfacility-text == "local0") then {
    action(
        type="omfile"
        file="/var/log/haproxy/haproxy.log"
        template="HAProxyLogFormat"
        fileOwner="root"
        fileGroup="root"
        fileCreateMode="0640"
    )
    stop
}
